name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install django
    - name: Run Django unit tests
      run: |
        source venv/bin/activate
        python manage.py test
